name: Deploy Documentation

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing to gh-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/generated
          force_orphan: true  # Creates a single-commit history on gh-pages branch
          commit_message: 'docs: update documentation' 